name: Build Image and Push Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}    
        APP_ENV: ${{ secrets.APP_ENV }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MAILER_DSN: ${{ secrets.MAILER_DSN }}    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Inject Secrets into .env
        run: |
          sed -i "s|APP_ENV=.*|APP_ENV=$APP_ENV|g" .env
          sed -i "s|MYSQL_ROOT_PASSWORD=.*|MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD|g" .env
          sed -i "s|MYSQL_DATABASE=.*|MYSQL_DATABASE=$MYSQL_DATABASE|g" .env
          sed -i "s|MYSQL_USER=.*|MYSQL_USER=$MYSQL_USER|g" .env
          sed -i "s|MYSQL_PASSWORD=.*|MYSQL_PASSWORD=$MYSQL_PASSWORD|g" .env
          sed -i "s|MAILER_DSN=.*|MAILER_DSN=$MAILER_DSN|g" .env

      - name: Build Docker Image
        run: docker build -t $REGISTRY_NAME/bondiz-blog -f ./docker/php/Dockerfile .

      - name: Log in to Docker Registry
        run: echo $REGISTRY_PASSWORD | docker login $REGISTRY_NAME -u $REGISTRY_USERNAME --password-stdin
      
      - name: Push Docker Image
        run: docker push $REGISTRY_NAME/bondiz-blog
  